name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: |
        docker build -t networth-tracker:${{ github.sha }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag networth-tracker:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/networth-tracker-backend:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/networth-tracker-backend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Heroku
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

    - name: Push and Release to Heroku
      run: |
        heroku container:push web --app your-heroku-app-name
        heroku container:release web --app your-heroku-app-name
